import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/component/Navbar";
import Footer from "@/component/Footer";

import "react-responsive-carousel/lib/styles/carousel.min.css";
import Wrapper from "@/component/Wrapper";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="">
            <body className="font-primary min-h-screen">
                <Wrapper>
                    <header>
                        <Navbar />
                    </header>

                    <main className="space-y-20 mb-20">{children}</main>

                    <footer>
                        <Footer />
                    </footer>
                </Wrapper>
            </body>
        </html>
    );
}
