import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/component/Navbar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="">
            <body className="font-primary min-h-screen pb-20">
                <header>
                    <Navbar />
                </header>
                <main>{children}</main>
            </body>
        </html>
    );
}
